### ISSUE TITLE
Poor contrast in dark style

### ISSUE THREAD

**Issue by lukors** [JeysonFlores/switcher#1]
The sun and moon and settings icons have really poor contrast in dark style.

![image](https://user-images.githubusercontent.com/1719884/145961269-61593f2d-e6eb-4e48-8768-71578db0f3c8.png)

**Comment by JeysonFlores** [comment]
Oh yeah, I forgot that this was a thing. I let it this way because when dark mode is activated Buttons have some kind of border/blurry gradient and the CSS lines I wrote to quit the border from Light mode's buttons doesn't work on dark mode. Kind of strange but I'm not really that good at CSS so when I was writing the app I decided to put it apart while I was coding more important things.

**Comment by JeysonFlores** [comment]
I'll use this issue as a thread to discuss the changes on the icon contrast.
