### ISSUE TITLE
Change accent color too

### ISSUE THREAD

**Issue by lukors** [JeysonFlores/switcher#5]
Different wallpapers go well with different accent colors. It would be nice if an accent color could be chosen for each wallpaper as well.

A good example of this is the default Odin wallpaper and its dark version. The default wallpaper goes well with Blueberry, but the dark version goes better with Mint.

**Comment by JeysonFlores** [comment]
The way switcher triggers the mode switching events is thru the `Granite.Settings` class, which is basically a wrapper around the DBus signal that sends the desktop when the Style Mode is changed. Granite doesn't provide any interface to catch Accent Colors settings signal (You can check the class documentation [here](https://valadoc.org/granite/Granite.Settings.html)). However it seems that in the code of the [Desktop Plug](https://github.com/elementary/switchboard-plug-pantheon-shell) when the accent color changes, it does creates a signal on DBus, so in order to implement just the triggering of the signal, a wrapper for it must be handcoded.

**Comment by JeysonFlores** [comment]
I think this improvement would be more pertinent in the case of a version 2. Which will come until other issues and UI stuff get solved. There are more urgent things to be fixed,

**Comment by lukors** [comment]
I just noticed that in elementary OS 6.1 there is a setting to automatically pick an accent color from the background image.

This fills my needs very nicely, so as far as I'm concerned this issue can be closed unless you want to keep it.
